### ISSUE TITLE
There's no way to reproduce the testing results

### ISSUE THREAD

**Issue by ghost** [stealthsploit/OneRuleToRuleThemStill#4]
[This post](https://in.security/2023/01/10/oneruletorulethemstill-new-and-improved/) gives this table:

| Dataset | OneRuleToRuleThemAll | OneRuleToRuleThemStill |
| --- | --- | --- |
| Lifeboat (~4.3m unique hashes) | 2,960,729 cracked | 2,960,729 cracked |
| LastFM (~21m unique hashes) | 14,634,893 cracked | 14,634,893 cracked |

However, it's impossible to reproduce the above results using publicly available (see hashmob.net) leaks.

OneRuleToRuleThemStill only cracks 14627604 out of 20872334 Last.fm-2016 hashes, which is 7289 hashes short of the number in the table.
```
Recovered........: 14627604/20872334 (70.08%) Digests (total), 14627604/20872334 (70.08%) Digests (new)
```

As for Lifeboat, there are 108 missing hashes, too.

```
Recovered........: 2960621/4330829 (68.36%) Digests (total), 2960621/4330829 (68.36%) Digests (new)
```

**Comment by stealthsploit** [comment]
As discussed, the datasets used were different and hence the numbers were different. This has now been resolved on Discord.

**Comment by kernc** [comment]
These are small datasets to use for verification. Can you try https://github.com/berzerk0/Probable-Wordlists ?
